server:
  http2:
    enabled: true

# Actuator
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

springdoc:
  swagger-ui:
    path: /doc
  show-actuator: true
  default-produces-media-type: application/json

spring:
  application:
    name: flow-translator-webapp
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
    deserialization:
      fail-on-unknown-properties: false

# TODO: add more namespace mappings
keip:
  namespaceMappings:
    - eipNamespace: integration
      xmlNamespace: http://www.springframework.org/schema/integration
      schemaLocation: https://www.springframework.org/schema/integration/spring-integration.xsd
    - eipNamespace: jms
      xmlNamespace: http://www.springframework.org/schema/integration/jms
      schemaLocation: https://www.springframework.org/schema/integration/jms/spring-integration-jms.xsd