# Some minor errors were present in some spring-integration schemas.
# The XMLs were corrected and served on a local http server.
# The errors for each schema (if present) are commented below

schemas:
  - alias: "integration"
    namespace: "http://www.springframework.org/schema/integration"
    location: "https://www.springframework.org/schema/integration/spring-integration-5.2.xsd"
    excludedElements:
      - "selector-chain"
      - "spel-property-accessors"
      - "converter"
      - "chain"

  - alias: "jms"
    namespace: "http://www.springframework.org/schema/integration/jms"
    location: "https://www.springframework.org/schema/integration/jms/spring-integration-jms-5.2.xsd"

  - alias: "http"
    namespace: "http://www.springframework.org/schema/integration/http"
    location: "https://www.springframework.org/schema/integration/http/spring-integration-http-5.2.xsd"

  # The 'nio-locker' element had no type defined, causing the schema walker to throw an exception.
  #  - alias: "file"
  #    namespace: "http://www.springframework.org/schema/integration/file"
  #    location: "https://www.springframework.org/schema/integration/file/spring-integration-file-5.2.xsd"
  #    excludedElements:
  #      - "locker"
  #      - "nio-locker"

  - alias: "kafka"
    namespace: "http://www.springframework.org/schema/integration/kafka"
    location: "https://www.springframework.org/schema/integration/kafka/spring-integration-kafka-3.1.xsd"

  - alias: "groovy"
    namespace: "http://www.springframework.org/schema/integration/groovy"
    location: "https://www.springframework.org/schema/integration/groovy/spring-integration-groovy-5.2.xsd"

  - alias: "ftp"
    namespace: "http://www.springframework.org/schema/integration/ftp"
    location: "https://www.springframework.org/schema/integration/ftp/spring-integration-ftp-5.2.xsd"

  - alias: "sftp"
    namespace: "http://www.springframework.org/schema/integration/sftp"
    location: "https://www.springframework.org/schema/integration/sftp/spring-integration-sftp-5.2.xsd"

  - alias: "tcp/udp"
    namespace: "http://www.springframework.org/schema/integration/ip"
    location: "https://www.springframework.org/schema/integration/ip/spring-integration-ip-5.2.xsd"

  - alias: "web-services"
    namespace: "http://www.springframework.org/schema/integration/ws"
    location: "https://www.springframework.org/schema/integration/ws/spring-integration-ws-5.2.xsd"
#
#  - alias: "xml"
#    namespace: "http://www.springframework.org/schema/integration/xml"
#    location: "https://www.springframework.org/schema/integration/xml/spring-integration-xml-5.2.xsd"

# schemaLocations provided here will override any schemaLocations provided in <xsd:import> elements
# for the listed namespaces
importedSchemaLocations:
  - namespace: "http://www.springframework.org/schema/integration"
    location: "https://www.springframework.org/schema/integration/spring-integration-5.2.xsd"
  - namespace: "http://www.springframework.org/schema/beans"
    location: "https://www.springframework.org/schema/beans/spring-beans-4.3.xsd"
  - namespace: "http://www.springframework.org/schema/tool"
    location: "https://www.springframework.org/schema/tool/spring-tool-4.3.xsd"